name: example-environment
channels:
  - conda-forge
dependencies:
  - pip=20.3.3
  - python=3.6.12
  - readline=8.0
  - setuptools=51.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scikit-learn
  - pyyaml
  - pip : 
    - absl-py==0.11.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==3.4.0
    - ipykernel==5.4.2
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.6
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - send2trash==1.5.0
    - sklearn
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - testpath==0.4.4
    - tornado==6.1
  
